api_username:
api_password:
api_url: https://ha117-1.overkiz.com/enduser-mobile-web/enduserAPI
api_user_agent: aasivak

mqtt_discovery_prefix: homeassistant
mqtt_state_prefix: hikumo/state
mqtt_command_prefix: hikumo/command
mqtt_reset_topic: hikumo/reset
mqtt_host: 127.0.0.1
mqtt_client_name: aasivak
mqtt_discovery: on
mqtt_config_retain: on
mqtt_state_retain: on
#mqtt_username:
#mqtt_password: 

#http_proxy: socks5://localhost:9050
#https_proxy: socks5://localhost:9050

temperature_unit: °C

action_delay: 0.5

refresh_delays:
  - 3
  - 5
  - 10
  - 30
refresh_delay_randomness: 2

logging_level: INFO
